eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9510/eureka/
spring:
  application:
    name: IRemote Messager
  freemarker:
    # 设置模板后缀名
    suffix: .ftl
    # 设置文档类型
    content-type: text/html
    # 设置页面编码格式
    charset: UTF-8
    # 设置页面缓存
    cache: false
    # 设置ftl文件路径
    template-loader-path:
    - classpath:/templates/ftl
    # 设置静态文件路径，js,css等
  mvc:
    static-path-pattern: /static/**
